Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

============ RESTART: C:\Users\dell\Desktop\coding\spider coding.py ============
content of the spider text.txt
['spider man no way home as spider was cheated by mysterio and he was not knowing that his identity is revealed then comes the reason for the doctor strange to come in to action because spidey and his freinds were in difficulty as all were thinking that he is not the hero but the villain of the whole scenario then doctor strange casts the spell that everyone will forget that peter parker is the spider man and then multiverse starts with the flow all the villains come together and fight with the three heroes spider man of three multiverse coming together whom we are seeing since the childhhood.']
lines seperated by '#':-
spider#
man#
no#
way#
home#
as#
spider#
was#
cheated#
by#
mysterio#
and#
he#
was#
not#
knowing#
that#
his#
identity#
is#
revealed#
then#
comes#
the#
reason#
for#
the#
doctor#
strange#
to#
come#
in#
to#
action#
because#
spidey#
and#
his#
freinds#
were#
in#
difficulty#
as#
all#
were#
thinking#
that#
he#
is#
not#
the#
hero#
but#
the#
villain#
of#
the#
whole#
scenario#
then#
doctor#
strange#
casts#
the#
spell#
that#
everyone#
will#
forget#
that#
peter#
parker#
is#
the#
spider#
man#
and#
then#
multiverse#
starts#
with#
the#
flow#
all#
the#
villains#
come#
together#
and#
fight#
with#
the#
three#
heroes#
spider#
man#
of#
three#
multiverse#
coming#
together#
whom#
we#
are#
seeing#
since#
the#
childhhood.#

